<?php

if( !class_exists('ctf_fonts') )
{
	/**
	 *
	 * Contain normal/google fonts
	 * 
	 */
	class ctf_fonts {

		public $not_google_fonts = array(
										'Arial',
										'Arial Black',
										'Verdana',
										'Impact',
										'Helvetica',
										'Georgia',
										'Tahoma',
										'Courier New'
									);
		public $fonts = array(  // important to use " '' " not ' "" ' on css key.
								// check add_font_used() function below
					        'Arial'				=>	"'Arial', 'Verdana' sans-serif"  , 
					        'Arial Black'		=>  "'Arial Black', 'Arial Black', 'Gadget', sans-serif",
					        'Verdana'			=>	"'Verdana', 'Arial' sans-serif"  ,
					        'Impact'			=>  "'Impact', 'Impact5', 'Charcoal6', sans-serif",
					        'Helvetica'			=>  "'Helvetica', 'Arial', sans-serif",
					        'Georgia'			=>  "'Georgia1', 'Georgia', serif",
					        'Tahoma'			=>  "'Tahoma', 'Geneva', sans-serif",
					        'Courier New'		=>  "'Courier New', 'Courier New', monospace",	
					        '---------- Google Fonts ----------' => "",   
					        'Ubuntu'			=>	"'Ubuntu', 'Arial', 'Verdana' sans-serif" ,  
					        'Lobster'			=>	"'Lobster', cursive",
					        'Questrial'			=>	"'Questrial', sans-serif" ,
					        'Denk One'			=>	"'Denk One', sans-serif",
					        'Source Sans Pro'	=>	"'Source Sans Pro', sans-serif",
					        'Dosis'				=>	"'Dosis', sans-serif",
					        'Abel'				=>	"'Abel', sans-serif",
					        'Crafty Girls'		=>	"'Crafty Girls', cursive",
					        'Noto Sans'			=>	"'Noto Sans', sans-serif",
					        'Droid Sans'		=>	"'Droid Sans', sans-serif",
					        'Cantata One'		=>	"'Cantata One', serif",
					        'Permanent Marker'	=>	"'Permanent Marker', cursive",
					        'Unkempt'			=>	"'Unkempt', cursive",
					        'Jockey One'		=>	"'Jockey One', sans-serif",
					        'Lato'				=>	"'Lato', sans-serif",
					        'Arvo'				=>	"'Arvo', serif",
					        'Cabin'				=>	"'Cabin', sans-serif",
					        'Playfair Display'	=>	"'Playfair Display', serif",
					        'Economica'			=>	"'Economica', sans-serif",
					        'News Cycle'		=>	"'News Cycle', sans-serif",
					        'Lora'				=>	"'Lora', serif",
					        'PT Sans'			=>	"'PT Sans', sans-serif",
					        'Cherry Cream Soda'	=>	"'Cherry Cream Soda', cursive",
					        'PT Sans Narrow'	=>	"PT Sans Narrow', sans-serif",
					        'Ropa Sans'			=>	"'Ropa Sans', sans-serif",
					        'Cabin Condensed'	=>	"'Cabin Condensed', sans-serif",
					        'Philosopher'		=>	"'Philosopher', sans-serif",
					        'Istok Web'			=>	"'Istok Web', sans-serif",
					        'Arimo'				=>	"'Arimo', sans-serif",
					        'Quicksand'			=>	"'Quicksand', sans-serif",
					        'The Girl Next Door'=>	"'The Girl Next Door', cursive",
					        'Marck Script'		=>	"'Marck Script', cursive",
					        'Droid Sans Mono'	=>	"'Droid Sans Mono', sans-serif",
					        'Josefin Sans'		=>	"'Josefin Sans', sans-serif",
					        'Bitter'			=>	"'Bitter', serif",
					        'PT Serif'			=>	"'PT Serif', serif",
					        'Kreon'				=>	"'Kreon', serif",
					        'Anton'				=>	"'Anton', sans-serif",
					        'Shadows Into Light'=>	"'Shadows Into Light', cursive",
					        'Rokkitt'			=>	"'Rokkitt', serif",
					        'Josefin Slab'		=>	"'Josefin Slab', serif",
					        'Fredoka One'		=>	"'Fredoka One', cursive",
					        'Libre Baskerville'	=>	"'Libre Baskerville', serif",
					        'Gloria Hallelujah'	=>	"'Gloria Hallelujah', cursive",
					        'Calligraffitti'	=>	"'Calligraffitti', cursive",
					        'Exo'				=>	"'Exo', sans-serif",
					        'Asap'				=>	"'Asap', sans-serif",
					        'Cantarell'			=>	"'Cantarell', sans-serif",
					        'Muli'				=>	"'Muli', sans-serif",
					        'Ubuntu Condensed'	=>	"'Ubuntu Condensed', sans-serif",
					        'EB Garamond'		=>	"'EB Garamond', serif",
					        'Droid Serif'		=>	"'Droid Serif', serif",
					        'Open Sans'			=>	"'Open Sans', sans-serif",
					        'Oswald'			=>	"'Oswald', sans-serif",
					        'Open Sans Condensed'=>	"'Open Sans Condensed', sans-serif",
					        'Roboto'			=> "'Roboto', sans-serif",
					        'Roboto Condensed'	=> "'Roboto Condensed', sans-serif",
					        'Yanone Kaffeesatz'	=> "'Yanone Kaffeesatz', sans-serif",
					        'Nunito'			=> "'Nunito', sans-serif",
					        'Raleway'			=> "'Raleway', sans-serif",
					        'Francois One'		=> "'Francois One', sans-serif",
					        'Cuprum'			=> "'Cuprum', sans-serif",
					        'Montserrat'		=> "'Montserrat', sans-serif",
					        'Play'				=> "'Play', sans-serif",
					        'Titillium Web'		=> "'Titillium Web', sans-serif",
					        'Oxygen'			=> "'Oxygen', sans-serif",
					        'Fjalla One'		=> "'Fjalla One', sans-serif",
					        'Merriweather'		=> "'Merriweather', serif",
					        'Merriweather Sans'	=> "'Merriweather Sans', sans-serif",
					        'Changa One'		=> "'Changa One', cursive",
					        'PT Sans Caption'	=> "'PT Sans Caption', sans-serif",
					        'Signika'			=> "'Signika', sans-serif",
					        'Maven Pro'			=> "'Maven Pro', sans-serif",
					        'Vollkorn'			=> "'Vollkorn', serif",
					        'Inconsolata'		=> "'Inconsolata', sans-serif",
					        'Dancing Script'	=> "'Dancing Script', cursive",
					        'Coming Soon'		=> "'Coming Soon', cursive",
					        'Pacifico'			=> "'Pacifico', cursive",
					        'Nobile'			=> "'Nobile', sans-serif",
					        'Archivo Narrow'	=> "'Archivo Narrow', sans-serif",
					        'Comfortaa'			=> "'Comfortaa', cursive",
					        'Chewy'				=> "'Chewy', cursive",
					        'Marvel'			=> "'Marvel', sans-serif",
					        'Leckerli One'		=> "'Leckerli One', cursive",
					        'Pontano Sans'		=> "'Pontano Sans', sans-serif",
					        'Bree Serif'		=> "'Bree Serif', serif",
					        'Luckiest Guy'		=> "'Luckiest Guy', cursive",
					        'Amatic SC'			=> "'Amatic SC', cursive",
					        'Rock Salt'			=> "'Rock Salt', cursive",
					        'Righteous'			=> "'Righteous', cursive",
					        'Telex'				=> "'Telex', sans-serif",
					        'Squada One'		=> "'Squada One', cursive",
					        'Karla'				=> "'Karla', sans-serif",
					        'Black Ops One'		=> "'Black Ops One', cursive",
					        'Molengo'			=> "'Molengo', sans-serif",
					        'Old Standard TT'	=> "'Old Standard TT', serif",
					        'Lobster Two'		=> "'Lobster Two', cursive",
					        'Archivo Black'		=> "'Archivo Black', sans-serif",
					        'Indie Flower'		=> "'Indie Flower', cursive",
					        'Crimson Text'		=> "'Crimson Text', serif",
					        'Quattrocento Sans'	=> "'Quattrocento Sans', sans-serif",
					        'Satisfy'			=> "'Satisfy', cursive",
	    				); 

	} // end class 

} // end if